/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'xenxui' at '2016/8/3 下午 3:03' with Gradle 2.14
 *
 * @author xenxui, @date 2016/8/3 下午 3:03
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
